version: '3.0'

services:
  product_db:
    container_name: product_db
    image: mongo
    ports:
      - "27017:27017"
    restart:
        always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: baza
