version: '3.0'

services:
  order_db:
    container_name: order_db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart:
        always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    env_file:
      - kafka.env
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
    env_file:
      - zookeeper.env
