version: '3.0'

services:
  order_db:
    container_name: order_db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart:
        always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
