spring:
  application:
    name: order-service
  datasource:
    url: ${CONN_STR}
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
server:
  port: 0