version: '3.0'

services:
  inventory_db:
    container_name: inventory_db
    image: mongo
    ports:
      - "27018:27017"
    restart:
        always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: baza
